export const SERVICES = [
  {
    id: 'developpement-web',
    icon: 'Monitor',
    titleFr: 'Développement Web',
    titleEn: 'Web Development',
    summaryFr: 'Sites vitrines, applications web et plateformes sur mesure, modernes et performantes.',
    summaryEn: 'Custom websites, web applications and platforms, modern and performant.',
    slug: 'developpement-web',
    stackKey: 'stackWeb',
  },
  {
    id: 'applications-mobiles',
    icon: 'Smartphone',
    titleFr: 'Applications Mobiles',
    titleEn: 'Mobile Applications',
    summaryFr: 'Applications iOS et Android natives ou cross-platform pour vos besoins métiers.',
    summaryEn: 'Native or cross-platform iOS and Android apps for your business needs.',
    slug: 'applications-mobiles',
    stackKey: 'stackMobile',
  },
  {
    id: 'logiciels-gestion',
    icon: 'Code2',
    titleFr: 'Logiciels de Gestion',
    titleEn: 'Management Software',
    summaryFr: 'ERP, CRM, systèmes de gestion sur mesure adaptés à votre organisation.',
    summaryEn: 'Custom ERP, CRM and management systems tailored to your organization.',
    slug: 'logiciels-gestion',
    stackKey: 'stackLogiciel',
  },
  {
    id: 'formations',
    icon: 'GraduationCap',
    titleFr: 'Formations en Informatique',
    titleEn: 'IT Training',
    summaryFr: 'Formations pratiques en développement web, mobile et outils digitaux.',
    summaryEn: 'Practical training in web, mobile development and digital tools.',
    slug: 'formations',
    stackKey: 'stackFormation',
  },
] as const
